api_name: []
items:
- _type: module
  children:
  - cntk.ops.tests.evaluation_test.test_edit_distance_error
  - cntk.ops.tests.evaluation_test.test_lambda_rank
  - cntk.ops.tests.evaluation_test.test_ndcg
  - cntk.ops.tests.evaluation_test.test_op_classification_error
  - cntk.ops.tests.evaluation_test.test_op_classification_error_with_axis
  - cntk.ops.tests.evaluation_test.test_op_cross_entropy_with_soft_max
  - cntk.ops.tests.evaluation_test.test_op_cross_entropy_with_soft_max_and_axis
  - cntk.ops.tests.evaluation_test.test_op_squared_error
  - cntk.ops.tests.evaluation_test.test_sequence_grad_as_numpy_false
  fullName: cntk.ops.tests.evaluation_test
  module: cntk.ops.tests.evaluation_test
  name: evaluation_test
  references:
  - fullName: cntk.ops.tests.evaluation_test.test_edit_distance_error
    isExternal: false
    name: test_edit_distance_error
    parent: ''
    uid: cntk.ops.tests.evaluation_test.test_edit_distance_error
  - fullName: cntk.ops.tests.evaluation_test.test_lambda_rank
    isExternal: false
    name: test_lambda_rank
    parent: ''
    uid: cntk.ops.tests.evaluation_test.test_lambda_rank
  - fullName: cntk.ops.tests.evaluation_test.test_ndcg
    isExternal: false
    name: test_ndcg
    parent: ''
    uid: cntk.ops.tests.evaluation_test.test_ndcg
  - fullName: cntk.ops.tests.evaluation_test.test_op_classification_error
    isExternal: false
    name: test_op_classification_error
    parent: ''
    uid: cntk.ops.tests.evaluation_test.test_op_classification_error
  - fullName: cntk.ops.tests.evaluation_test.test_op_classification_error_with_axis
    isExternal: false
    name: test_op_classification_error_with_axis
    parent: ''
    uid: cntk.ops.tests.evaluation_test.test_op_classification_error_with_axis
  - fullName: cntk.ops.tests.evaluation_test.test_op_cross_entropy_with_soft_max
    isExternal: false
    name: test_op_cross_entropy_with_soft_max
    parent: ''
    uid: cntk.ops.tests.evaluation_test.test_op_cross_entropy_with_soft_max
  - fullName: cntk.ops.tests.evaluation_test.test_op_cross_entropy_with_soft_max_and_axis
    isExternal: false
    name: test_op_cross_entropy_with_soft_max_and_axis
    parent: ''
    uid: cntk.ops.tests.evaluation_test.test_op_cross_entropy_with_soft_max_and_axis
  - fullName: cntk.ops.tests.evaluation_test.test_op_squared_error
    isExternal: false
    name: test_op_squared_error
    parent: ''
    uid: cntk.ops.tests.evaluation_test.test_op_squared_error
  - fullName: cntk.ops.tests.evaluation_test.test_sequence_grad_as_numpy_false
    isExternal: false
    name: test_sequence_grad_as_numpy_false
    parent: ''
    uid: cntk.ops.tests.evaluation_test.test_sequence_grad_as_numpy_false
  source:
    id: evaluation_test
    path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/ops/tests/evaluation_test.py
    remote:
      branch: '/bin/sh: 1: git: not found'
      path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/ops/tests/evaluation_test.py
      repo: null
    startLine: 0
  type: Namespace
  uid: cntk.ops.tests.evaluation_test
- _type: function
  fullName: cntk.ops.tests.evaluation_test.test_edit_distance_error
  module: cntk.ops.tests.evaluation_test
  name: test_edit_distance_error
  source:
    id: test_edit_distance_error
    path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/ops/tests/evaluation_test.py
    remote:
      branch: '/bin/sh: 1: git: not found'
      path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/ops/tests/evaluation_test.py
      repo: null
    startLine: 284
  syntax:
    summary: ''
  type: Method
  uid: cntk.ops.tests.evaluation_test.test_edit_distance_error
- _type: function
  fullName: cntk.ops.tests.evaluation_test.test_lambda_rank
  module: cntk.ops.tests.evaluation_test
  name: test_lambda_rank
  source:
    id: test_lambda_rank
    path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/ops/tests/evaluation_test.py
    remote:
      branch: '/bin/sh: 1: git: not found'
      path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/ops/tests/evaluation_test.py
      repo: null
    startLine: 225
  syntax:
    summary: ''
  type: Method
  uid: cntk.ops.tests.evaluation_test.test_lambda_rank
- _type: function
  fullName: cntk.ops.tests.evaluation_test.test_ndcg
  module: cntk.ops.tests.evaluation_test
  name: test_ndcg
  source:
    id: test_ndcg
    path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/ops/tests/evaluation_test.py
    remote:
      branch: '/bin/sh: 1: git: not found'
      path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/ops/tests/evaluation_test.py
      repo: null
    startLine: 254
  syntax:
    summary: ''
  type: Method
  uid: cntk.ops.tests.evaluation_test.test_ndcg
- _type: function
  fullName: cntk.ops.tests.evaluation_test.test_op_classification_error
  module: cntk.ops.tests.evaluation_test
  name: test_op_classification_error
  source:
    id: test_op_classification_error
    path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/ops/tests/evaluation_test.py
    remote:
      branch: '/bin/sh: 1: git: not found'
      path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/ops/tests/evaluation_test.py
      repo: null
    startLine: 136
  syntax:
    summary: ''
  type: Method
  uid: cntk.ops.tests.evaluation_test.test_op_classification_error
- _type: function
  fullName: cntk.ops.tests.evaluation_test.test_op_classification_error_with_axis
  module: cntk.ops.tests.evaluation_test
  name: test_op_classification_error_with_axis
  source:
    id: test_op_classification_error_with_axis
    path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/ops/tests/evaluation_test.py
    remote:
      branch: '/bin/sh: 1: git: not found'
      path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/ops/tests/evaluation_test.py
      repo: null
    startLine: 183
  syntax:
    summary: ''
  type: Method
  uid: cntk.ops.tests.evaluation_test.test_op_classification_error_with_axis
- _type: function
  fullName: cntk.ops.tests.evaluation_test.test_op_cross_entropy_with_soft_max
  module: cntk.ops.tests.evaluation_test
  name: test_op_cross_entropy_with_soft_max
  source:
    id: test_op_cross_entropy_with_soft_max
    path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/ops/tests/evaluation_test.py
    remote:
      branch: '/bin/sh: 1: git: not found'
      path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/ops/tests/evaluation_test.py
      repo: null
    startLine: 27
  syntax:
    summary: ''
  type: Method
  uid: cntk.ops.tests.evaluation_test.test_op_cross_entropy_with_soft_max
- _type: function
  fullName: cntk.ops.tests.evaluation_test.test_op_cross_entropy_with_soft_max_and_axis
  module: cntk.ops.tests.evaluation_test
  name: test_op_cross_entropy_with_soft_max_and_axis
  source:
    id: test_op_cross_entropy_with_soft_max_and_axis
    path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/ops/tests/evaluation_test.py
    remote:
      branch: '/bin/sh: 1: git: not found'
      path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/ops/tests/evaluation_test.py
      repo: null
    startLine: 73
  syntax:
    summary: ''
  type: Method
  uid: cntk.ops.tests.evaluation_test.test_op_cross_entropy_with_soft_max_and_axis
- _type: function
  fullName: cntk.ops.tests.evaluation_test.test_op_squared_error
  module: cntk.ops.tests.evaluation_test
  name: test_op_squared_error
  source:
    id: test_op_squared_error
    path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/ops/tests/evaluation_test.py
    remote:
      branch: '/bin/sh: 1: git: not found'
      path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/ops/tests/evaluation_test.py
      repo: null
    startLine: 110
  syntax:
    summary: ''
  type: Method
  uid: cntk.ops.tests.evaluation_test.test_op_squared_error
- _type: function
  fullName: cntk.ops.tests.evaluation_test.test_sequence_grad_as_numpy_false
  module: cntk.ops.tests.evaluation_test
  name: test_sequence_grad_as_numpy_false
  source:
    id: test_sequence_grad_as_numpy_false
    path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/ops/tests/evaluation_test.py
    remote:
      branch: '/bin/sh: 1: git: not found'
      path: root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/ops/tests/evaluation_test.py
      repo: null
    startLine: 292
  syntax:
    summary: ''
  type: Method
  uid: cntk.ops.tests.evaluation_test.test_sequence_grad_as_numpy_false
